# -*- coding: utf-8 -*-
"""financial-advisor-fine-tuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19mIQOGxuGshatZeEyVvDsoEXvnmkAJ2S

# 🧠 Fine-Tuning LLaMA to be a Financial Advisor (Supports LoRA and QLoRA)

This notebook demonstrates best practices for fine-tuning a LLaMA model using **LoRA** or **QLoRA** with [Unsloth](https://unsloth.ai/), based on the [financial-advisor-100 dataset](https://www.superteams.ai/blog/guide-to-fine-tune-your-llm-for-building-your-own-financial-advisor).

## Environment Set-up
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install --no-deps bitsandbytes accelerate xformers==0.0.29.post3 peft trl triton
# !pip install --no-deps cut_cross_entropy unsloth_zoo
# !pip install sentencepiece protobuf datasets huggingface_hub hf_transfer
# !pip install -q unsloth

"""## Load Base Model (LoRA vs QLoRA)

"""

from unsloth import FastLanguageModel
from google.colab import userdata
import torch

# Choose method: "LoRA" or "QLoRA"
fine_tuning_method = "QLoRA"

if fine_tuning_method == "LoRA":
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name="meta-llama/Llama-3.2-3B",
        max_seq_length=2048,
        dtype=torch.float16,
        load_in_4bit=False,
        token=userdata.get("HF_TOKEN")
    )
elif fine_tuning_method == "QLoRA":
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name="unsloth/Meta-Llama-3.1-8B-Instruct-bnb-4bit",
        max_seq_length=2048,
        dtype=torch.float16,
        load_in_4bit=True,
        token=userdata.get("HF_TOKEN")
    )

"""# Chat Template Configuration"""

# Set chat template for GGUF compatibility
chat_template = """
{{ bos_token }}
<|start_header_id|>system<|end_header_id|>
{{ system_message }}<|eot_id|>
{% for message in messages %}
<|start_header_id|>{{ message['role'] }}<|end_header_id|>
{{ message['content'] }}<|eot_id|>
{% endfor %}
<|start_header_id|>assistant<|end_header_id|>
"""

if tokenizer.chat_template != chat_template:
    tokenizer.chat_template = chat_template
    print("✅ Set custom chat_template for GGUF compatibility.")

"""## LoRA/QLoRA Configuration"""

# LoRA fine-tuning configuration for FastLanguageModel using PEFT
# Reference: https://huggingface.co/docs/peft/v0.11.0/en/package_reference/lora#peft.LoraConfig

from peft import LoraConfig

# Target transformer modules to inject LoRA adapters into
# These are common projection layers in attention and MLP blocks of transformer models
target_modules = [
    "q_proj",     # Query projection (self-attention)
    "k_proj",     # Key projection
    "v_proj",     # Value projection
    "o_proj",     # Output projection from attention
    "gate_proj",  # Gating layer in FFN
    "up_proj",    # Feedforward network up-projection
    "down_proj"   # Feedforward network down-projection
]

# Flag to determine whether to include token embedding layer for training (e.g., when adding special tokens)
train_embeddings = False
if train_embeddings:
    target_modules.append("lm_head")  # lm_head is typically the output embedding layer

# LoRA configuration dictionary for clarity and reuse
lora_config = {
    "r": 16,  # Rank of the low-rank adapter matrices. Lower = smaller adapter, less compute.
              # According to the original LoRA paper, small r (e.g. 4–16) performs well.

    "target_modules": target_modules,  # List of layer names to apply LoRA to

    "lora_alpha": 16,  # Scaling factor for the LoRA weights.
                       # Larger alpha increases the impact of adapters (defaults often 16–64).

    "lora_dropout": 0.0,  # Dropout rate applied to the LoRA layers during training.
                          # Unsloth suggests 0.0 for best performance unless overfitting.

    "bias": "none",  # "none": no bias training; saves memory and computation.
                     # Alternatives: "all" or "lora_only" (rarely used in practice).

    "use_gradient_checkpointing": "unsloth",  # Activates gradient checkpointing. Saves VRAM by recomputing intermediate activations.
                                              # "unsloth" enables long-context training optimally.

    "random_state": 3407,  # Seed for reproducibility (affects adapter initialization).

    "use_rslora": False,  # Whether to scale LoRA weights by 1/sqrt(r) (recommended by HF in some cases).
                          # Often disabled when using tuned alpha directly.

    "loftq_config": None,  # Used only if integrating with LoftQ (quantization-aware LoRA).
                           # Leave as None for standard full-precision LoRA.
}

# Inject LoRA adapters into the base model using PEFT
model = FastLanguageModel.get_peft_model(
    model,
    **lora_config
)

# Confirm the configured target modules
print("LoRA modules applied to:", model.peft_config["default"].target_modules)

"""## Load & Format Dataset"""

from datasets import load_dataset

# Load the dataset (forcing redownload to avoid cache bugs)
dataset = load_dataset(
    "nihiluis/financial-advisor-100",
    split="train",
    download_mode="force_redownload"
)

print(dataset.column_names)

# Reformat to instruction-tuning format
def format_instruction(example):
    return {
        "instruction": example["question"],
        "input": "",  # optional input if needed
        "output": example["answer"]
    }

dataset = dataset.map(format_instruction)
dataset = dataset.remove_columns([col for col in dataset.column_names if col not in ["instruction", "input", "output"]])

"""## Tokenization"""

# Tokenize each sample into prompt format
def tokenize(example):
    messages = [
        {"role": "system", "content": "You are a helpful and knowledgeable financial advisor specializing in providing clear, actionable advice to a wide range of financial questions."},
        {"role": "user", "content": example["instruction"]},
        {"role": "assistant", "content": example["output"]},
    ]
    prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=False)
    return tokenizer(prompt, truncation=True, padding="max_length", max_length=2048)

tokenized_dataset = dataset.map(tokenize, remove_columns=dataset.column_names)

"""## Training"""

from transformers import DataCollatorForLanguageModeling, Trainer, TrainingArguments

training_args = TrainingArguments(
    output_dir="./financial_llama",
    num_train_epochs=5,
    per_device_train_batch_size=2,
    gradient_accumulation_steps=4,
    optim="adamw_8bit" if fine_tuning_method == "QLoRA" else "adamw_torch",
    learning_rate=2e-4,
    fp16=True,
    logging_steps=10,
    seed=42,
    save_strategy="no",
    report_to="none"
)

data_collator = DataCollatorForLanguageModeling(tokenizer, mlm=False)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset,
    tokenizer=tokenizer,
    data_collator=data_collator
)

trainer.train()

"""## Inference"""

from transformers import TextStreamer

def ask_financial_question(question: str, max_new_tokens: int = 200):
    FastLanguageModel.for_inference(model)
    messages = [
        {"role": "system", "content": "You are a helpful and knowledgeable financial advisor."},
        {"role": "user", "content": question}
    ]
    prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
    streamer = TextStreamer(tokenizer)
    print("📩 Answer:")
    _ = model.generate(**inputs, streamer=streamer, max_new_tokens=max_new_tokens)

ask_financial_question("How should I prioritize paying off debt vs investing?")

save_path = "./qlora-financial-advisor"
tokenizer.save_pretrained(save_path)

"""## Save & Push"""

if fine_tuning_method == "LoRA":

    model.save_pretrained(save_path)

    # Push to huggingface
    model.push_to_hub("jordynojeda/Llama-3.2-3B-financial-advisor-lora", token=userdata.get("HF_TOKEN"))
    tokenizer.push_to_hub("jordynojeda/Llama-3.2-3B-financial-advisor-lora", token=userdata.get("HF_TOKEN"))

elif fine_tuning_method == "QLoRA":

    model.save_pretrained(save_path)

    # Push to huggingface
    model.push_to_hub("jordynojeda/Meta-Llama-3.1-8B-Instruct-bnb-4bit-financial-advisor-qlora", token=userdata.get("HF_TOKEN"))
    tokenizer.push_to_hub("jordynojeda/Meta-Llama-3.1-8B-Instruct-bnb-4bit-financial-advisor-qlora", token=userdata.get("HF_TOKEN"))

# Push to hugging face
model.push_to_hub_gguf(
    "jordynojeda/Meta-Llama-3.1-8B-Instruct-bnb-4bit-financial-advisor-qlora-GGUF",
    tokenizer,
    quantization_method="q4_k_m",
    token=userdata.get("HF_TOKEN")
)

"""## ✅ Summary

- ✅ Supports both **LoRA** and **QLoRA** fine-tuning
- ✅ Based on Unsloth for efficient training
- ✅ Uses Hugging Face datasets and trainer for ease
- ✅ Outputs a Hugging Face-ready adapter model

Test and compare performance between `LoRA` and `QLoRA` by switching `fine_tuning_method` at the top.
"""
