name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: huggingface/hub-action@main
        with:
          repo: jordynojeda/Fine-Tuned-LLM-with-Retrieval-Augmented-Generation-FT-RAG
          token: ${{ secrets.HF_TOKEN }}
